---


# snap

- name: check firefox snap
  stat:
    path: "{{ custom_ca_firefox_snap_path }}/{{ custom_ca_firefox_snap_version }}"
  register: t_custom_ca_firefox_snap_path

- block:

    - name: ensure snap firefox config dir
      file:
        path: "{{ custom_ca_firefox_snap_config_dir }}"
        owner: root
        group: "{{ root_group }}"
        mode: "0755"
        state: directory

    # TODO: reload, merge, deploy

    - name: deploy policies for snap
      template:
        src: firefox/policies.json
        dest: "{{ custom_ca_firefox_snap_policies_json_path }}"
        owner: root
        group: "{{ root_group }}"
        mode: "0644"

  when: t_custom_ca_firefox_snap_path.stat.exists
